name: Build
on:
  # push:
  #   branches: "main"
  #   paths-ignore:
  #     - README.md
  #     - LICENSE
  #     - .gitignore
  #     - .github/**
  #     - "!.github/workflows/build.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/build.yml"
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }
          - { os: macos-latest }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          sudo apt-get install gettext -y
      - run: |
          make configure
          ./configure --prefix=/usr/local
          make all
        working-directory: git
      - run: tree -a || ls -A
