name: Build
on:
  # push:
  #   branches: "main"
  #   paths-ignore:
  #     - README.md
  #     - LICENSE
  #     - .gitignore
  #     - .github/**
  #     - "!.github/workflows/build.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/build.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - if: runner.os == 'Linux'
        run: sudo apt-get install gettext -y
      - run: |
          make configure
          ./configure --prefix=$(pwd)/out
          make all
          sudo make install
        working-directory: git
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: git/out
