name: gh release create
on:
  push:
    branches: "main"
    paths: git
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  build:
    uses: ./.github/workflows/build.yml
  gh-release-create:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: tree -a
