name: Update git
on:
  push:
    branches: "main"
    paths: .github/workflows/update-git.yml
  schedule:
    - cron: "19 */6 * * *"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  update-git:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # A Deploy Key with write permissions to trigger 'on: push'.
          ssh-key: ${{ secrets.SELF_DEPLOY_KEY }}
          submodules: true
      - run: |
          latest_git_tag=$(gh api repos/git/git/tags --jq '.[].name' | head -n1)
          git -C git fetch --all --tags --prune
          local_git_tag=$(git -C git describe --tags)
          if [[ $local_git_tag != $latest_git_tag ]]; then
            git -C git checkout "$latest_git_tag"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions4git/add-commit-push@v1
